import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import Anthropic from '@anthropic-ai/sdk';
import {
  analyzeAllocation,
  computeWealthHealth,
  topWealthActions,
  type Allocation,
  type AssetClass,
  type RiskTolerance,
} from '@lcos/core';
import { PrismaService } from '../prisma/prisma.service';
import { FinancialSnapshotService } from '../common/financial-snapshot.service';

export interface CoachMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface CoachReply {
  reply: string;
  /** True when the answer was generated by the LLM; false for the deterministic fallback. */
  ai: boolean;
}

export interface SecondOpinion {
  /** Deterministic allocation findings from @lcos/core (always present). */
  current: Record<string, number>;
  recommended: Record<string, number>;
  drift: Record<string, number>;
  findings: string[];
  /** Narrative review (LLM when configured, else a deterministic summary). */
  review: string;
  ai: boolean;
}

/**
 * AI Wealth Coach. Grounds Claude in the user's *real* financial snapshot (net worth,
 * scores, top actions) so guidance is personalised, not generic. Falls back to a
 * deterministic, rules-based answer when no ANTHROPIC_API_KEY is configured, so the
 * feature degrades gracefully instead of erroring.
 */
@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);
  private readonly client: Anthropic | null;
  private readonly model: string;

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
    private readonly snapshots: FinancialSnapshotService,
  ) {
    const apiKey = this.config.get<string>('ai.apiKey');
    this.model = this.config.get<string>('ai.model') ?? 'claude-sonnet-4-6';
    this.client = apiKey ? new Anthropic({ apiKey }) : null;
  }

  /** Build a compact, factual summary of the user's finances for grounding. */
  private async buildContext(userId: string): Promise<string> {
    const snapshot = await this.snapshots.assemble(userId);
    const { currency } = snapshot;

    // Score from the *real* snapshot (age, protection, retirement gap) — no hardcoding.
    const report = computeWealthHealth(FinancialSnapshotService.toScoreInput(snapshot));
    const actions = topWealthActions(report);

    const inr = (minor: number) => `${currency} ${(minor / 100).toLocaleString('en-IN')}`;
    const protection = [
      snapshot.hasTermCover ? `term life ${inr(snapshot.existingLifeCoverMinor)}` : 'no term life',
      snapshot.hasHealthInsurance ? 'health insurance' : 'no health insurance',
    ].join(', ');
    return [
      `Base currency: ${currency}`,
      `Age: ${snapshot.age}`,
      `Net worth: ${inr(snapshot.netWorthMinor)} (assets ${inr(snapshot.assetsMinor)}, liabilities ${inr(snapshot.liabilitiesMinor)})`,
      `Annual income: ${inr(snapshot.annualIncomeMinor)}; monthly expenses: ${inr(snapshot.monthlyExpensesMinor)}`,
      `Risk tolerance: ${snapshot.riskTolerance}; dependents: ${snapshot.dependents}`,
      `Protection: ${protection}`,
      `Retirement: required corpus ${inr(snapshot.retirementRequiredCorpusMinor)}, projected gap ${inr(snapshot.retirementCorpusGapMinor)}`,
      `Life Capital Score: ${report.overall}/100 (band ${report.band})`,
      `Sub-scores: ${report.subScores.map((s) => `${s.label} ${s.score}`).join(', ')}`,
      `Top suggested actions: ${actions.map((a) => a.title).join('; ') || 'none — all areas healthy'}`,
    ].join('\n');
  }

  private static SYSTEM = [
    'You are the Life Capital OS Wealth Coach, a calm, encouraging financial coach for Indian families.',
    'Use the USER FINANCIAL SNAPSHOT provided to give specific, personalised, actionable guidance.',
    'Be concise (under 200 words), use INR, and prefer concrete next steps over generic theory.',
    'You are an educational coach, not a SEBI-registered advisor: do not recommend specific securities,',
    'and add a one-line reminder to consult a registered advisor for regulated product decisions.',
    'Never invent numbers that are not in the snapshot.',
  ].join(' ');

  async coach(userId: string, history: CoachMessage[]): Promise<CoachReply> {
    const context = await this.buildContext(userId);

    if (!this.client) {
      return { reply: this.fallback(context, history), ai: false };
    }

    try {
      const msg = await this.client.messages.create({
        model: this.model,
        max_tokens: 600,
        system: [
          { type: 'text', text: AiService.SYSTEM },
          // Cache the (stable) snapshot block to cut cost on multi-turn chats.
          {
            type: 'text',
            text: `USER FINANCIAL SNAPSHOT:\n${context}`,
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: history.map((m) => ({ role: m.role, content: m.content })),
      });
      const reply = msg.content
        .filter((b): b is Anthropic.TextBlock => b.type === 'text')
        .map((b) => b.text)
        .join('\n')
        .trim();
      return { reply, ai: true };
    } catch (err) {
      this.logger.error(`Claude call failed: ${(err as Error).message}`);
      return { reply: this.fallback(context, history), ai: false };
    }
  }

  /** Deterministic answer when the LLM is unavailable — still grounded in real data. */
  private fallback(context: string, history: CoachMessage[]): string {
    const last = history[history.length - 1]?.content ?? '';
    return [
      'Here is what I can see from your finances right now:',
      '',
      context,
      '',
      last ? `You asked: "${last}".` : '',
      'The AI coach is not fully configured yet (no API key set), but based on your snapshot, focus on your lowest sub-scores first — they are where small actions move your Life Capital Score the most. For regulated product decisions, please consult a SEBI-registered advisor.',
    ]
      .filter(Boolean)
      .join('\n');
  }

  /**
   * AI Second Opinion — reviews the user's asset allocation. Deterministic drift
   * findings come from @lcos/core; Claude adds a narrative review when configured.
   */
  async secondOpinion(userId: string): Promise<SecondOpinion> {
    const [profile, accounts] = await Promise.all([
      this.prisma.profile.findUnique({ where: { userId } }),
      this.prisma.account.findMany({ where: { userId } }),
    ]);
    const risk = (profile?.riskTolerance as RiskTolerance) ?? 'moderate';

    // Aggregate non-liability balances by asset class into the allocation input.
    const byClass: Allocation = {};
    for (const a of accounts) {
      if (a.isLiability || !a.assetClass) continue;
      const k = a.assetClass as AssetClass;
      byClass[k] = (byClass[k] ?? 0) + Number(a.balanceMinor);
    }

    const analysis = analyzeAllocation(byClass, risk);
    const findings =
      analysis.suggestions.length > 0
        ? analysis.suggestions
        : ['Your allocation is close to the recommended mix for your risk profile.'];

    const base: Omit<SecondOpinion, 'review' | 'ai'> = {
      current: analysis.current,
      recommended: analysis.recommended,
      drift: analysis.drift,
      findings,
    };

    const factual = [
      `Risk profile: ${risk}`,
      `Current allocation (%): ${JSON.stringify(analysis.current)}`,
      `Recommended (%): ${JSON.stringify(analysis.recommended)}`,
      `Drift (pp): ${JSON.stringify(analysis.drift)}`,
      `Findings: ${findings.join('; ')}`,
    ].join('\n');

    if (!this.client) {
      return { ...base, review: `Allocation review:\n${factual}`, ai: false };
    }

    try {
      const msg = await this.client.messages.create({
        model: this.model,
        max_tokens: 500,
        system: [
          {
            type: 'text',
            text:
              'You are the Life Capital OS Second Opinion engine. Given an allocation analysis, ' +
              'write a concise (under 180 words) portfolio review for an Indian investor: call out ' +
              'concentration risk and the most important rebalancing moves, in plain English. ' +
              'Educational only, not a securities recommendation; remind them to consult a ' +
              'SEBI-registered advisor. Never invent numbers not present in the analysis.',
          },
        ],
        messages: [{ role: 'user', content: `ALLOCATION ANALYSIS:\n${factual}` }],
      });
      const review = msg.content
        .filter((b): b is Anthropic.TextBlock => b.type === 'text')
        .map((b) => b.text)
        .join('\n')
        .trim();
      return { ...base, review, ai: true };
    } catch (err) {
      this.logger.error(`Second Opinion LLM call failed: ${(err as Error).message}`);
      return { ...base, review: `Allocation review:\n${factual}`, ai: false };
    }
  }
}
